# Header
menu:
  主页: /
  归档: /archives
  杂谈: /categories/杂谈

# SubNav
subnav:
  github: "https://github.com/hugzh/"
  weibo: "http://weibo.com/u/2076290857"
  rss: "/atom.xml"
  #zhihu: "#"
  #douban: "#"
  mail: "sehuguozhi@163.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: /img/author.jpg
#是否开启分享
share_jia: true
share_addthis: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  伯乐在线: http://www.jobbole.com/
  慕课网: http://www.imooc.com/
  小胡子歌的博客: http://www.barretlee.com/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 16年毕业于中山大学，梦想做一枚天天向上的前端攻城狮
